#!/usr/bin/env bash

export TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-com.t3tools.t3code}"
export NPM_CONFIG_PREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/npm-global"
export NPM_CONFIG_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/npm"
export PATH="$NPM_CONFIG_PREFIX/bin:/app/bin:$PATH"

mkdir -p "$NPM_CONFIG_PREFIX" "$NPM_CONFIG_CACHE"

declare -a FLAGS=()

if [[ -n "$WAYLAND_DISPLAY" ]]; then
    if [[ -c /dev/nvidia0 ]]; then
        echo "Using NVIDIA on Wayland, disabling gpu sandbox"
        FLAGS+=(--disable-gpu-sandbox)
    fi

    echo "Running on native Wayland"
    FLAGS+=(--ozone-platform-hint=auto)
    FLAGS+=(--enable-wayland-ime)
    FLAGS+=(--wayland-text-input-version=3)
else
    echo "Running on X11"
fi

echo "Passing the following arguments to Electron:" "${FLAGS[@]}" "$@"
zypak-wrapper /app/bin/t3code/t3code "${FLAGS[@]}" "$@"
