#!/usr/bin/env bash

export TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-com.t3tools.t3code}"

declare -a FLAGS=()

if [[ -n "$WAYLAND_DISPLAY" ]]; then
    if [[ -c /dev/nvidia0 ]]; then
        echo "Using NVIDIA on Wayland, disabling gpu sandbox"
        FLAGS+=(--disable-gpu-sandbox)
    fi

    echo "Running on native Wayland"
    FLAGS+=(--ozone-platform-hint=auto)
    FLAGS+=(--enable-wayland-ime)
    FLAGS+=(--wayland-text-input-version=3)
else
    echo "Running on X11"
fi

echo "Passing the following arguments to Electron:" "${FLAGS[@]}" "$@"
zypak-wrapper /app/bin/t3code/t3code "${FLAGS[@]}" "$@"
